[debug] [2019-02-02T20:56:51.777Z] ----------------------------------------------------------------------
[debug] [2019-02-02T20:56:51.779Z] Command:       /usr/bin/node /usr/bin/firebase serve
[debug] [2019-02-02T20:56:51.779Z] CLI Version:   6.3.1
[debug] [2019-02-02T20:56:51.779Z] Platform:      linux
[debug] [2019-02-02T20:56:51.779Z] Node Version:  v11.6.0
[debug] [2019-02-02T20:56:51.780Z] Time:          Sat Feb 02 2019 15:56:51 GMT-0500 (Eastern Standard Time)
[debug] [2019-02-02T20:56:51.780Z] ----------------------------------------------------------------------
[debug] 
[debug] [2019-02-02T20:56:51.787Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2019-02-02T20:56:51.788Z] > authorizing via signed-in user
[debug] [2019-02-02T20:56:51.788Z] [iam] checking project utrition for permissions ["firebase.projects.get"]
[debug] [2019-02-02T20:56:51.789Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/utrition:testIamPermissions  

[debug] [2019-02-02T20:56:52.933Z] <<< HTTP RESPONSE 200
[debug] [2019-02-02T20:56:52.935Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/utrition  
 
[debug] [2019-02-02T20:56:56.417Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/data/r/utrition/service'...
[info] 
[debug] [2019-02-02T20:56:57.119Z] Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Object.mkdirSync (fs.js:775:3)
    at Object.assertLogsPath (/usr/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:77:32)
    at FunctionsEmulator.start (/usr/lib/node_modules/firebase-tools/lib/functionsEmulator.js:102:23)
    at Object.start (/usr/lib/node_modules/firebase-tools/lib/serve/functions.js:7:33)
    at /usr/lib/node_modules/firebase-tools/lib/serve/index.js:15:23
    at arrayMap (/usr/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at Function.map (/usr/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9556:14)
    at _serve (/usr/lib/node_modules/firebase-tools/lib/serve/index.js:13:26)
    at Command.module.exports.Command.description.option.option.option.option.before.action [as _action] (/usr/lib/node_modules/firebase-tools/lib/commands/serve.js:55:12)
[error] 
[error] Error: An unexpected error has occurred.
